#!/bin/sh

# Xcode Cloud runs this automatically after cloning the repository, before
# resolving/building. `Secrets.swift` is gitignored (it holds the Airtable
# PAT), so it's absent on a clean CI checkout — which makes
# `Secrets.airtableToken` "Cannot find 'Secrets' in scope". We regenerate it
# here from the AIRTABLE_PAT environment variable defined in the Xcode Cloud
# workflow (mark it Secret). The synchronized source group auto-includes any
# .swift under "Bindu Field/", so the generated file compiles into the target.

set -e

if [ -z "$AIRTABLE_PAT" ]; then
  echo "error: AIRTABLE_PAT is not set. Add it as a (Secret) environment variable" >&2
  echo "       in the Xcode Cloud workflow: Workflow > Environment > Environment Variables." >&2
  exit 1
fi

# CI_PRIMARY_REPOSITORY_PATH is the repo root Xcode Cloud checks out to.
SECRETS_PATH="${CI_PRIMARY_REPOSITORY_PATH}/Bindu Field/Secrets.swift"

cat > "$SECRETS_PATH" <<EOF
// Generated by ci_scripts/ci_post_clone.sh for Xcode Cloud. Not committed.
enum Secrets {
    static let airtableToken = "${AIRTABLE_PAT}"
}
EOF

echo "ci_post_clone: wrote ${SECRETS_PATH}"
